---
title: "Schwimmen"
author: 
- name: Kaspar Rufibach
  affiliation: Meiringen
date: "Letzte Aenderung: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "lubridate", "readxl", "tibble")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- "C:/rufibach/01_personal/05_Sport/40_reporting/"
path <- paste(getwd(), "/", sep = "")

source(paste(path, "/functions/input_touren.r", sep = ""))
source(paste(path, "/functions/schwimmen_print.r", sep = ""))

## =================================================================
## input data
## =================================================================
cy <- as.character(read_excel(paste(path, "data/currentyear.xlsx", sep = "")))
inp <- input_touren(path)
touren <- inp$touren
selectsport <- "Freiwasserschwimmen"
touren <- (touren %>% mutate(Distanz = hm_diff))
```


# Aktuelles Jahr {.tabset .tabset-fade .tabset-pills}

::: {.panel-tabset .nav-pills}

```{r, echo = FALSE, results = 'asis', message = FALSE, eval = TRUE}
t <- (touren %>% filter(sport == selectsport & year(touren$date) == cy & grepl("Alexander", beg) == FALSE) %>% group_by(date) %>% slice_tail() %>% schwimmen_print())
```

Anzahl Touren: `r nrow(t)`. 

## Nach Datum

```{r, echo = FALSE, results = 'asis', message = FALSE, eval = TRUE}
t1 <- (t %>% select(-beg) %>% arrange(date)) %>% rowid_to_column("Nr")
pander(t1)
```

## Nach Distanz

```{r, echo = FALSE, results = 'asis', message = FALSE, eval = TRUE}
thm <- (touren %>% filter(sport == selectsport & year(touren$date) == cy) %>% group_by(date) %>% arrange(desc(time), .by_group = TRUE) %>% schwimmen_print())
t1 <- (thm %>% select(-beg) %>% filter(is.na(Distanz) == FALSE) %>% arrange(desc(Distanz))) %>% rowid_to_column("Nr")
pander(t1)
```

## Nach Zeit pro 100m

```{r, echo = FALSE, results = 'asis', message = FALSE, eval = TRUE}
t1 <- (touren %>% filter(sport == selectsport & year(touren$date) == cy & grepl("Alexander", beg) == FALSE) %>% group_by(date) %>% schwimmen_print())
t1 <- (t1 %>% select(-beg)) %>% rowid_to_column("Nr")
pander(t1)
```

:::

# Nach Zeit pro 100m overall

Dieser Abschnitt sortiert die Touren absteigend nach min/100m.

```{r hm_h, echo = FALSE, results = 'asis', message = FALSE, eval = TRUE}
t <- (touren %>% filter(is.na(hm_h) == FALSE & sport == selectsport))
#t <- (t %>% group_by(paste(start, end, sep = "")) %>% arrange(desc(hm_h)) %>% slice(1) %>% ungroup())
t <- (t %>% schwimmen_print())
t1 <- (t %>% select(-beg))
pander(t1)
```







